export const englishTop200 = [
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
  "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
  "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
  "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
  "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
  "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
  "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
  "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
  "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
  "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
  "great", "between", "need", "large", "let", "home", "here", "right", "big", "high",
  "end", "small", "part", "long", "own", "old", "open", "same", "tell", "thing",
  "begin", "while", "last", "might", "few", "hand", "find", "place", "early", "keep",
  "head", "point", "turn", "move", "close", "play", "run", "seem", "help", "house",
  "world", "kind", "still", "start", "much", "read", "next", "line", "too", "mean",
  "each", "must", "set", "try", "ask", "change", "went", "light", "name", "school",
  "number", "real", "write", "every", "study", "show", "side", "been", "call", "both",
  "group", "often", "under", "story", "life", "left", "young", "girl", "sit", "less",
  "plan", "city", "build", "many", "put", "hard", "such", "face", "through", "child",
  "more", "never", "water", "those", "done", "again", "state", "grow", "may", "should",
];

export const englishTop1000 = [
  ...englishTop200,
  "person", "increase", "present", "consider", "become", "develop",
  "system", "service", "program", "question", "create", "result",
  "important", "bring", "include", "course", "problem", "produce",
  "country", "follow", "continue", "interest", "power", "provide",
  "company", "learn", "different", "level", "allow", "office",
  "possible", "political", "general", "government", "money",
  "fact", "process", "public", "market", "example", "reason",
  "several", "nature", "million", "support", "order", "special",
  "during", "report", "member", "control", "sense",
  "area", "action", "history", "policy", "future", "party",
  "social", "issue", "human", "force", "letter", "minute",
  "morning", "second", "value", "research", "body",
  "single", "quality", "piece", "model", "national", "center",
  "student", "class", "stand", "animal", "heart", "record",
  "table", "father", "month", "matter", "simply", "section",
  "decide", "return", "watch", "figure", "clear", "paper",
  "space", "ground", "form", "event", "picture", "offer",
  "strong", "total", "economic", "remember", "expect", "language",
  "reduce", "happy", "above", "price", "away", "period",
  "carry", "care", "hour", "window", "listen", "idea",
  "color", "voice", "energy", "role", "summer", "chance",
  "drive", "position", "project", "cover", "mother", "drop",
  "common", "modern", "century", "effort", "pretty", "charge",
  "garden", "note", "brother", "source", "personal", "computer",
  "network", "practice", "manager", "enjoy", "reach", "remain",
  "effect", "design", "street", "image", "itself", "phone",
  "either", "data", "local", "suggest", "pressure", "break",
  "evening", "camera", "surface", "store", "measure", "product",
  "doctor", "please", "film", "field", "type", "benefit",
  "indicate", "establish", "range", "statement", "officer", "private",
  "popular", "address", "discover", "property", "material",
  "reveal", "weapon", "culture", "agency", "argue", "debate",
  "account", "appear", "citizen", "threat", "challenge", "current",
  "exist", "director", "prevent", "contain", "protect",
  "accept", "relate", "serious", "suffer", "apply", "major",
  "beyond", "amount", "treatment", "perform", "economy", "campaign",
  "respond", "prepare", "assume", "involve", "behavior", "entire",
  "generation", "commercial", "movement", "explain", "improve", "edge",
  "structure", "official", "introduce", "adult", "shoulder", "manage",
  "partner", "physical", "spread", "collect", "operation", "hospital",
  "identify", "plant", "finish", "discuss", "agree", "choice",
  "article", "evidence", "front", "natural", "behind",
  "painting", "mission", "trouble", "impact", "ability", "maintain",
  "standard", "success", "defense", "attack", "interview",
  "author", "financial", "customer", "nation", "theory",
  "require", "describe", "audience", "receive", "magazine", "bit",
  "machine", "detail", "technology", "various", "condition",
  "leader", "media", "season", "soldier", "kitchen", "floor",
  "demand", "wonder", "approach", "pattern", "whatever",
  "attention", "resource", "exchange", "opinion", "arrive",
  "determine", "concern", "access", "education", "represent", "majority",
  "recently", "method", "region", "congress", "trade", "trial",
  "security", "growth", "income", "imagine", "reality", "employee",
  "decade", "compare", "performance", "direction", "enter", "strategy",
  "stuff", "budget", "risk", "foreign", "suddenly",
];
